# -*- coding: utf-8 -*-
"""PowerPoint_Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IHbdFy3mNeXExdYmiKZSKdDHjkg0HVux
"""

!pip install python-pptx

from pptx import Presentation

prs = Presentation()
title_slide_layout = prs.slide_layouts[0]

slide = prs.slides.add_slide(title_slide_layout)
title = slide.shapes.title
subtitle = slide.placeholders[1]

title.text = "Hello, World!"
subtitle.text = "Teste python Power Point"

prs.save('teste.pptx')