# -*- coding: utf-8 -*-
"""Plotly_Testes

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Oqljx-ql1N48Zub346xmLL2DU7JApdn7
"""

import numpy as np
import plotly.offline as pyo
import plotly.graph_objs as go

"""#Primeira aula - Scatter"""

np.random.seed(42)

random_x = np.random.randint(1, 101, 100)
random_y = np.random.randint(1, 100, 100)

data = [go.Scatter(x=random_x, y =random_y, mode='markers',
                   marker=dict(size=12,
                                color='rgb(51,204,153)',
                                symbol='pentagon',
                                line = {'width':2}))]
                                
layout = go.Layout(title="Hello First Plotly", xaxis= {'title':'My X Axis'},
                   yaxis=dict(title='My Y Axix'), hovermode='closest')
fig = go.Figure(data=data, layout=layout)

pyo.plot(fig, filename='scatter.html')

"""#Segunda aula - Line"""

np.random.seed(56)
x_values = np.linspace(0,1,100)
y_values = np.random.randn(100)

trace0 = go.Scatter(x=x_values, y=y_values+5,
                   mode='markers', name='markers')

trace1 = go.Scatter(x=x_values, y=y_values,
                    mode='lines', name='mylines')

trace2 = go.Scatter(x=x_values, y=y_values-5,
                    mode='lines+markers', name='testes')

data = [trace0, trace1, trace2]

layout = go.Layout(title='Line Charts')
fig = go.Figure(data=data, layout=layout)

pyo.plot(fig, filename='line3.html')

"""# Terceira aula - Line pt2"""

import pandas as pd

dados = pd.read_csv("https://raw.githubusercontent.com/Pierian-Data/Plotly-Dashboards-with-Dash/master/SourceData/nst-est2017-alldata.csv")
dados.head()

dados.shape

dados2 = dados[dados['DIVISION'] == '1']
dados2.set_index('NAME', inplace=True)
dados2.head()

lista_pop = [col for col in dados2.columns if col.startswith('POP')]
dados2 = dados2[lista_pop]
dados2.head()

dados2.shape

data = [go.Scatter(x=dados2.columns,y=dados2.loc[name],
                   mode='lines',name=name) for name in dados2.index]

pyo.plot(data, filename='line.html')

"""##Ex1"""

dados = pd.read_csv("https://raw.githubusercontent.com/Pierian-Data/Plotly-Dashboards-with-Dash/master/Data/2010YumaAZ.csv")
dados.head()

dados.shape

dias = ['TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY',
        'SUNDAY', 'MONDAY']

data = []

for dia in dias:
  trace = go.Scatter(x=dados['LST_TIME'],
                     y=dados[dados['DAY']==dia]['T_HR_AVG'], 
                     mode='lines', 
                     name=dia)
  data.append(trace)

#Outra forma de usar
data = [{
    'x': dados['LST_TIME'],
    'y': dados[dados['DAY']==dia]['T_HR_AVG'],
    'name': dia
} for dia in dados['DAY'].unique()]

layout = go.Layout(title='Temperatura diária')
fig = go.Figure(data=data, layout=layout)

pyo.plot(fig, filename="Ex1.html")

"""#Quarta Aula - Bar Chart"""

dados = pd.read_csv("https://raw.githubusercontent.com/Pierian-Data/Plotly-Dashboards-with-Dash/master/Data/2018WinterOlympics.csv")
dados.head()

dados.shape

trace1 = go.Bar(x=dados['NOC'], y=dados['Gold'], 
                name='Gold', marker={'color':'#FFD700'})

trace2 = go.Bar(x=dados['NOC'], y=dados['Silver'], 
                name='Silver', marker={'color':'#9EA0A1'})

trace3 = go.Bar(x=dados['NOC'], y=dados['Bronze'], 
                name='Bronze', marker={'color':'#CD7F32'})

#data = [go.Bar(x=dados['NOC'],y=dados['Total'])]
data = [trace1, trace2, trace3]
layout = go.Layout(title='Medals', barmode='stack')
fig = go.Figure(data=data, layout=layout)
pyo.plot(fig, filename="Bar2.html")

